# Generated by Django 2.2.6 on 2021-11-18 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kloter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='numberkloter',
            old_name='number',
            new_name='kloter_number',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='nama',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='juz',
            new_name='no_juz',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='nomer',
            new_name='nomer_kloter',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='periode',
            new_name='putaran',
        ),
    ]
