# Generated by Django 2.2.6 on 2021-11-18 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kloter', '0003_auto_20211118_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
